[package]
name = "cluster-job-monitor"
version = "0.1.0"
authors = ["Jiajie Chen <c@jia.je>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.9.0"
env_logger = "0.6"
log = "0.4"
tokio = { version = "0.2", features = ["macros", "time"] }