interval = 60
name = "slurm"

[scheduler]
type = "Slurm"
config = "squeue -O jobid,name,username,state"

[notification]
type = "Slack"
config = "https://hooks.slack.com/services/REDACTED/REDACTED/REDACTED"
